apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nyx
  template:
    metadata:
      labels:
        app: nyx
    spec:
      containers:
      - name: nyx
        image: nyx:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nyx-service
spec:
  selector:
    app: nyx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
