import { ModelOption } from '@src/types';

const RAW_AVAILABLE_MODELS: ModelOption[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // LUCIFER NATIVE AGENT (QWEN 2.5 1.5B ON GPU VIA RIG-CORE)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'lucifer-native',
    name: 'Lucifer',
    provider: 'nyx-native',
    status: 'ga',
    description: 'The native Lucifer agent embodied in Qwen 2.5 1.5B running 100% on GPU via Rig-Core & TurboVec RAG.',
    specs: { contextWindow: '8K', maxOutput: '4K', modality: 'Text' },
    features: ['Embodied Lucifer Agent', '100% GPU Offload (Rig-Core)', 'TurboVec Vector RAG & Live Tools'],
    pros: ['Direct GPU Execution', 'Complete Privacy', 'Full Tool Control'],
    cons: ['Requires local GPU or Vulkan runtime'],
  },
  // ═══════════════════════════════════════════════════════════════════════════════
  // GEMINI DIRECT MODELS
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'gemini-3.6-flash',
    name: 'Gemini 3.6 Flash',
    provider: 'gemini',
    description: 'Flagship Gemini 3.6 Flash model (July 2026) — ultra-fast multimodal inference & deep reasoning.',
    status: 'ga',
    specs: { contextWindow: '1M', maxOutput: '32K', modality: 'Multimodal' },
    features: ['Ultra-high speed generation', 'Native multimodal input support', 'Agentic workflow optimization'],
    pros: ['Next-gen speed & intelligence', '1M Token Context Window'],
    cons: ['Slightly lower reasoning depth than Pro tier'],
    limits: { rpm: 15, tpm: 1000000, rpd: 1500 },
  },
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    provider: 'gemini',
    description: 'High-performance Gemini 3.5 Flash model for agentic and coding workflows.',
    status: 'ga',
    specs: { contextWindow: '1M', maxOutput: '32K', modality: 'Multimodal' },
    features: ['High-speed tier', 'Multimodal input support'],
    pros: ['High Speed & Low Latency', '1M Context Window'],
    cons: ['Risk of Hallucinations compared to Pro tier'],
    limits: { rpm: 15, tpm: 1000000, rpd: 1500 },
  },
  {
    id: 'gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'gemini',
    description: 'Gemini 3.1 Pro frontier reasoning model for complex coding and logic tasks.',
    status: 'ga',
    specs: { contextWindow: '2M', maxOutput: '64K', modality: 'Multimodal' },
    features: ['Frontier reasoning capability', 'Complex instruction following', 'Deep logic synthesis'],
    pros: ['Top-tier reasoning depth', 'Massive 2M context window'],
    cons: ['Higher latency than Flash tier'],
    limits: { rpm: 5, tpm: 250000, rpd: 50 },
  },
  {
    id: 'gemini-3.5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    provider: 'gemini',
    description: 'Lightweight Gemini 3.5 Flash Lite model for ultra-low latency high-volume tasks.',
    status: 'ga',
    specs: { contextWindow: '1M', maxOutput: '32K', modality: 'Multimodal' },
    features: ['Engineered for maximum cost-efficiency', 'Full multimodal input support'],
    pros: ['Ultra-fast inference latency', 'High throughput'],
    cons: ['Tailored for speed over deep code generation'],
    limits: { rpm: 30, tpm: 1000000, rpd: 2000 },
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'gemini',
    description: 'Official Google Gemini 2.5 Flash model balancing deep reasoning and low-latency.',
    status: 'ga',
    specs: { contextWindow: '1M', maxOutput: '32K', modality: 'Multimodal' },
    features: ['High-speed generation', 'Multimodal text, image, audio, video support'],
    pros: ['Official Google API model', 'High speed & low latency', '1M Context Window'],
    cons: ['Slightly lower reasoning depth than Pro tier'],
    limits: { rpm: 15, tpm: 1000000, rpd: 1500 },
  },
  // ═══════════════════════════════════════════════════════════════════════════════
  // OPENROUTER CLOUD MODELS (FREE & HIGH-LIMIT TIERS)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'openrouter/auto',
    name: 'Auto Router (OpenRouter Free)',
    provider: 'openrouter',
    description: 'OpenRouter dynamic auto-router — routes requests to the best available free cloud model.',
    status: 'ga',
    specs: { contextWindow: '128K', maxOutput: '8K', modality: 'Text' },
    features: ['Automatic free tier routing', 'High availability fallback', 'Agent & web search compatible'],
    pros: ['Zero configuration needed', 'Always online fallback'],
    cons: ['Dynamically selected backend model'],
  },
  {
    id: 'deepseek/deepseek-r1:free',
    name: 'DeepSeek R1 Free (OpenRouter)',
    provider: 'openrouter',
    status: 'ga',
    description: "DeepSeek's flagship R1 frontier reasoning model (Free Tier) with chain-of-thought.",
    specs: { contextWindow: '64K', maxOutput: '8K', modality: 'Text' },
    features: ['Chain-of-thought reasoning', 'Math & logic synthesis', 'Full UI think box integration'],
    pros: ['Top-tier reasoning capability', 'Free tier availability'],
    cons: ['Higher latency during peak hours'],
  },
  {
    id: 'deepseek/deepseek-chat:free',
    name: 'DeepSeek V3 Free (OpenRouter)',
    provider: 'openrouter',
    status: 'ga',
    description: "DeepSeek's flagship V3 ultra-efficient architecture (Free Tier).",
    specs: { contextWindow: '64K', maxOutput: '8K', modality: 'Text' },
    features: ['High-speed text & code generation', 'Deep context understanding'],
    pros: ['Exceptional speed & quality', 'Free tier usage'],
    cons: ['Strict rate limits during traffic spikes'],
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'Llama 3.3 70B Free (OpenRouter)',
    provider: 'openrouter',
    status: 'ga',
    description: "Meta's flagship open-weights 70B model (Free Tier) with 128k context.",
    specs: { contextWindow: '128K', maxOutput: '8K', modality: 'Text' },
    features: ['128K massive context window', 'State-of-the-art open instruction tuning'],
    pros: ['Huge context capacity', 'Free tier usage'],
    cons: ['Rate limited to 20 RPM'],
  },
  {
    id: 'qwen/qwen-2.5-coder-32b-instruct:free',
    name: 'Qwen 2.5 Coder 32B Free (OpenRouter)',
    provider: 'openrouter',
    status: 'ga',
    description: "Alibaba's specialized coding & software engineering model (Free Tier).",
    specs: { contextWindow: '32K', maxOutput: '8K', modality: 'Text' },
    features: ['Code generation & bug fixing', 'Syntax verification', 'Refactoring & architectural design'],
    pros: ['Top open-weights coding model', 'Free tier usage'],
    cons: ['Tailored specifically for code'],
  },
  {
    id: 'qwen/qwq-32b:free',
    name: 'Qwen QwQ 32B Reasoning Free (OpenRouter)',
    provider: 'openrouter',
    status: 'ga',
    description: "Qwen's dedicated reasoning model (Free Tier) for complex logic and math.",
    specs: { contextWindow: '32K', maxOutput: '8K', modality: 'Text' },
    features: ['Deep chain-of-thought thinking', 'Complex problem solving'],
    pros: ['Free reasoning alternative', 'High math accuracy'],
    cons: ['Thinking overhead on simple queries'],
  },
  {
    id: 'google/gemini-2.0-flash-exp:free',
    name: 'Gemini 2.0 Flash Free (OpenRouter)',
    provider: 'openrouter',
    status: 'ga',
    description: "Google Gemini 2.0 Flash experimental model (Free Tier).",
    specs: { contextWindow: '1M', maxOutput: '8K', modality: 'Multimodal' },
    features: ['Ultra-fast response time', '1M token context window', 'Multimodal capability'],
    pros: ['1M context window', 'Free tier access'],
    cons: ['Experimental model release'],
  },
  {
    id: 'mistralai/mistral-small-24b-instruct-2501:free',
    name: 'Mistral Small 24B Free (OpenRouter)',
    provider: 'openrouter',
    status: 'ga',
    description: "Mistral AI 24B instruct model (Free Tier) engineered for speed & precision.",
    specs: { contextWindow: '32K', maxOutput: '8K', modality: 'Text' },
    features: ['Low latency generation', 'Precise structured JSON/Markdown formatting'],
    pros: ['Very fast generation', 'Free tier access'],
    cons: ['Smaller parameter size'],
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1 (OpenRouter Pro)',
    provider: 'openrouter',
    status: 'ga',
    description: "DeepSeek's frontier reasoning model featuring chain of thought.",
    specs: { contextWindow: '64K', maxOutput: '8K', modality: 'Text' },
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3 (OpenRouter Pro)',
    provider: 'openrouter',
    status: 'ga',
    description: "DeepSeek's flagship V3 model on OpenRouter.",
    specs: { contextWindow: '64K', maxOutput: '8K', modality: 'Text' },
  },

  {
    id: 'gemma-4-31b-it',
    name: 'Gemma 4 31B',
    provider: 'gemini',
    status: 'ga',
    description: "Google's best open weights model — reasoning and math. Limits: 15 RPM, unlimited TPM, 1500 RPD.",
    specs: { contextWindow: '256K', maxOutput: '8K', modality: 'Text' },
    features: ['Strong reasoning and math capabilities', 'Open weights architecture'],
    pros: ['Excellent reasoning for its size', 'High instruction-following capability'],
    cons: ['Text modality only'],
    limits: { rpm: 15, tpm: null, rpd: 1500 },
  },
  {
    id: 'gemma-4-26b-a4b-it',
    name: 'Gemma 4 26B MoE',
    provider: 'gemini',
    status: 'ga',
    description: "Gemma 4 Mixture-of-Experts model — high throughput with advanced reasoning.",
    specs: { contextWindow: '128K', maxOutput: '8K', modality: 'Text' },
    features: ['Mixture-of-Experts architecture for high throughput', 'Advanced reasoning capability'],
    pros: ['High throughput', 'Efficient for complex reasoning tasks'],
    cons: ['Text modality only'],
    limits: { rpm: 15, tpm: null, rpd: 1500 },
  },
  // LOCAL PROVIDERS (NYX-NATIVE)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'qwen2.5-1.5b-instruct-native',
    name: 'Qwen 2.5 1.5B Instruct (Native GPU / Rig-Core)',
    provider: 'nyx-native',
    status: 'ga',
    description: 'Ultra-fast local model running 100% in GPU VRAM with Rig-Core & TurboVec RAG. Host RAM <150MB, zero cloud latency.',
    specs: { contextWindow: '8K', maxOutput: '4K', modality: 'Text' },
    features: ['100% GPU offload (28 layers in VRAM)', 'Rig-Core Agent & TurboVec RAG integration', 'Instant local token generation (>60 t/s)'],
    pros: ['Ultra-low RAM usage (<150MB)', '100% private offline execution', 'Zero API cost'],
    cons: ['Requires local GPU or Vulkan runtime'],
  },
];

// Deduplicate by ID to prevent duplicate entries in the model selector
const ALLOWED_PROVIDERS = ['gemini', 'openrouter', 'nyx-native'];
const _seen = new Set<string>();
export const AVAILABLE_MODELS: ModelOption[] = RAW_AVAILABLE_MODELS.filter((m) =>
  ALLOWED_PROVIDERS.includes(m.provider)
).filter((m) => {
  if (_seen.has(m.id)) return false;
  _seen.add(m.id);
  return true;
});
