apiVersion: v1
kind: ServiceAccount
metadata:
  name: nyx-fluent-bit
  namespace: nyx-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nyx-fluent-bit
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nyx-fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nyx-fluent-bit
subjects:
- kind: ServiceAccount
  name: nyx-fluent-bit
  namespace: nyx-production
