import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { createPortal } from 'react-dom';
import DOMPurify from 'dompurify';
import { fitSvgToResponseWidth } from './CodeBlock';

export interface SvgDiagramCardProps {
  svgCode: string;
  className?: string;
}

const SANITIZE_CONFIG: any = {
  USE_PROFILES: { svg: true, svgFilters: true },
  PARSER_MEDIA_TYPE: 'image/svg+xml',
};

/**
 * SvgDiagramCard
 * Renders editorial SVG diagrams generated by models with double-click expand/minimize.
 * Double-clicking expands the diagram to fit the entire screen.
 * Double-clicking again minimizes it back to its normal size in the chat page.
 * Strictly without extra buttons or toolbars.
 */
export const SvgDiagramCard: React.FC<SvgDiagramCardProps> = ({ svgCode, className }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  // Close on Escape key when expanded and lock body scroll
  useEffect(() => {
    if (!isExpanded) return;

    const originalOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setIsExpanded(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      document.body.style.overflow = originalOverflow;
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isExpanded]);

  const sanitizedInlineHtml = useMemo(() => {
    if (!svgCode?.trim()) return '';
    const fitted = fitSvgToResponseWidth(svgCode);
    return DOMPurify.sanitize(fitted, SANITIZE_CONFIG);
  }, [svgCode]);

  const sanitizedExpandedHtml = useMemo(() => {
    if (!svgCode?.trim()) return '';
    // In expanded mode, ensure root SVG scales to uniformly fit the screen bounds
    let expanded = fitSvgToResponseWidth(svgCode);
    expanded = expanded.replace(/<svg\b([^>]*)>/i, (_, attrs) => {
      const clean = attrs
        .replace(/\bwidth=["'][^"']*["']/gi, '')
        .replace(/\bheight=["'][^"']*["']/gi, '')
        .replace(/\bpreserveAspectRatio=["'][^"']*["']/gi, '')
        .trim();
      return `<svg ${clean} width="100%" height="100%" preserveAspectRatio="xMidYMid meet">`;
    });
    return DOMPurify.sanitize(expanded, SANITIZE_CONFIG);
  }, [svgCode]);

  const handleDoubleClick = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
    setIsExpanded((prev) => !prev);
  }, []);

  if (!svgCode?.trim()) return null;

  return (
    <>
      {/* Normal in-chat diagram card */}
      <div
        onDoubleClick={handleDoubleClick}
        title="Double-click to expand"
        className={`my-3 w-full rounded-xl border border-white/10 bg-[#000000] overflow-hidden flex items-center justify-center cursor-pointer select-none transition-transform duration-150 active:scale-[0.995] [&>svg]:w-full [&>svg]:h-auto [&>svg]:max-w-full [&>svg]:block ${className || ''}`}
      >
        <div
          className="w-full flex items-center justify-center [&>svg]:w-full [&>svg]:h-auto [&>svg]:max-w-full [&>svg]:block"
          dangerouslySetInnerHTML={{ __html: sanitizedInlineHtml }}
        />
      </div>

      {/* Expanded fullscreen overlay — fits entire screen, double-click minimizes */}
      {isExpanded &&
        createPortal(
          <div
            onDoubleClick={handleDoubleClick}
            title="Double-click to minimize"
            className="fixed inset-0 z-[99999] bg-[#000000]/95 backdrop-blur-xl flex items-center justify-center p-4 md:p-8 cursor-pointer select-none animate-in fade-in duration-150"
          >
            <div
              className="w-full h-full max-w-[96vw] max-h-[96vh] flex items-center justify-center [&>svg]:w-full [&>svg]:h-full [&>svg]:max-w-full [&>svg]:max-h-full [&>svg]:object-contain [&>svg]:block"
              dangerouslySetInnerHTML={{ __html: sanitizedExpandedHtml }}
            />
          </div>,
          document.body
        )}
    </>
  );
};
