global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nyx-backend'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['nyx-backend:3000', 'nyx-backend:3001']
