import { Octokit } from '@octokit/rest';

interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
}

export class GitHubIntegration {
  private octokit: Octokit;
  private config: GitHubConfig;

  constructor(config: GitHubConfig) {
    this.config = config;
    this.octokit = new Octokit({ auth: config.token });
  }

  async createPRFromChat(
    chatTitle: string,
    files: Array<{ path: string; content: string }>,
    baseBranch: string = 'main'
  ): Promise<string> {
    // Create new branch
    const branchName = `nyx-${Date.now()}`;
    const { data: ref } = await this.octokit.git.getRef({
      owner: this.config.owner,
      repo: this.config.repo,
      ref: `heads/${baseBranch}`
    });

    await this.octokit.git.createRef({
      owner: this.config.owner,
      repo: this.config.repo,
      ref: `refs/heads/${branchName}`,
      sha: ref.object.sha
    });

    // Create or update files
    for (const file of files) {
      try {
        // Get existing file to update
        const { data: existing } = await this.octokit.repos.getContent({
          owner: this.config.owner,
          repo: this.config.repo,
          path: file.path,
          ref: branchName
        });

        await this.octokit.repos.createOrUpdateFileContents({
          owner: this.config.owner,
          repo: this.config.repo,
          path: file.path,
          message: `Update ${file.path} via NYX`,
          content: Buffer.from(file.content).toString('base64'),
          sha: (existing as any).sha,
          branch: branchName
        });
      } catch {
        // File doesn't exist, create new
        await this.octokit.repos.createOrUpdateFileContents({
          owner: this.config.owner,
          repo: this.config.repo,
          path: file.path,
          message: `Create ${file.path} via NYX`,
          content: Buffer.from(file.content).toString('base64'),
          branch: branchName
        });
      }
    }

    // Create PR
    const { data: pr } = await this.octokit.pulls.create({
      owner: this.config.owner,
      repo: this.config.repo,
      title: chatTitle,
      head: branchName,
      base: baseBranch,
      body: 'Generated by NYX AI Assistant'
    });

    return pr.html_url;
  }
}
