name: Deploy
on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [completed]
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Lowercase Repository Name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - run: |
          kubectl set image deployment/nyx-server nyx=ghcr.io/${{ env.REPO_LC }}:${{ github.sha }} -n nyx-production
          kubectl rollout status deployment/nyx-server -n nyx-production
