import { ModelOption } from '../types.js';

/**
 * NVIDIA NIM (NVIDIA Inference Microservices) Catalog
 * Endpoint: https://integrate.api.nvidia.com/v1/chat/completions
 * Documentation: https://build.nvidia.com/explore/discover
 * Free Developer Tier: 40 RPM, 10,000 RPD (1,000 free build credits upon sign-up at build.nvidia.com)
 */
export const NVIDIA_MODELS: ModelOption[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // VERIFIED OFFICIAL NVIDIA NIM MODELS (Directly available via build.nvidia.com)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'meta/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta flagship open 70B parameter model hosted on NVIDIA high-speed NIM infrastructure with TensorRT-LLM acceleration.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window with TensorRT-LLM acceleration',
      'Advanced coding, agentic reasoning, and multilingual synthesis',
      'Native function and tool calling',
      'High token generation rate on NVIDIA HGX cluster',
    ],
    pros: ['Frontier-class open model capability', 'Very fast inference speed'],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'deepseek-ai/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'DeepSeek R1 frontier open reasoning model with full chain-of-thought mathematical reasoning hosted on NVIDIA NIM.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '16,384 (16K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '128K Context Window',
      'Full deep thinking and chain-of-thought step-by-step reasoning',
      'Benchmark-leading math, code, and scientific problem solving',
      'NVIDIA DGX Cloud TensorRT-LLM execution',
    ],
    pros: ['World-class reasoning capabilities', 'Native thinking token streams'],
    cons: ['Higher latency due to chain-of-thought generation'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'deepseek-ai/deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'DeepSeek V3 671B MoE (37B active) general-purpose flagship model on NVIDIA NIM with TensorRT-LLM fp8.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      '671B MoE architecture with exceptional coding and writing fluency',
      'Function calling and schema enforcement',
    ],
    pros: ['Ultra-fast response speed for MoE', 'Top-tier general benchmark performance'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    name: 'Llama 3.1 Nemotron 70B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA custom-aligned 70B model with RLHF/DPO designed for superior human preference, instruction following, and reasoning.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'NVIDIA NeMo alignment for top LMSYS Chatbot Arena human preference scores',
      'Advanced tool calling and structured formatting',
    ],
    pros: ['Exceptional instruction adherence', 'NVIDIA-tuned accuracy'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-51b-instruct',
    name: 'Llama 3.1 Nemotron 51B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA high-efficiency 51B neural architecture with extreme token throughput and low latency.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: false,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'High-throughput architecture for fast micro-services',
      'Native function calling',
    ],
    pros: ['Blazing-fast token generation', 'Low latency'],
    cons: ['Slightly lower reasoning depth than 70B'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.1-405b-instruct',
    name: 'Llama 3.1 405B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta frontier 405B parameter model served across multi-node NVIDIA DGX SuperPODs with TensorRT-LLM.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'Largest open weights foundation model (405 Billion parameters)',
      'Enterprise-grade complex reasoning and code generation',
    ],
    pros: ['Unmatched knowledge base and problem solving'],
    cons: ['High resource footprint'],
    limits: { rpm: 20, tpm: null, rpd: 5000 },
  },
  {
    id: 'meta/llama-3.1-8b-instruct',
    name: 'Llama 3.1 8B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Lightweight, high-speed 8B instruction model optimized on NVIDIA NIM for sub-10ms time-to-first-token.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: false,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'Extremely low latency and high concurrency',
      'Function calling and JSON schema generation',
    ],
    pros: ['Fastest generation speed', 'Economical'],
    cons: ['Limited complex mathematical reasoning'],
    limits: { rpm: 60, tpm: null, rpd: 20000 },
  },
  {
    id: 'meta/llama-3.2-90b-vision-instruct',
    name: 'Llama 3.2 90B Vision Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta flagship multimodal vision model on NVIDIA NIM with TensorRT-LLM visual encoder acceleration.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Multimodal',
    },
    capabilities: {
      vision: true,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'High-resolution image understanding, diagram extraction, and document visual QA',
      'Dual vision-text attention mechanism',
    ],
    pros: ['Powerful visual understanding', 'Enterprise accuracy on charts/diagrams'],
    cons: ['Slightly slower TTFT for large images'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/gemma-2-27b-it',
    name: 'Gemma 2 27B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'Google lightweight powerhouse 27B model on NVIDIA NIM with TensorRT-LLM fp8.',
    specs: {
      contextWindow: '8,192 (8K)',
      maxOutput: '4,096 (4K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: false,
      toolCalling: true,
    },
    supportsThinking: false,
    features: ['High parameter efficiency', 'Fast response times', 'Strong general reasoning'],
    pros: ['Efficient throughput', 'Compact size with strong benchmark scores'],
    cons: ['8K context window'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'microsoft/phi-4',
    name: 'Phi-4',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'Microsoft 14B state-of-the-art synthetic reasoning model hosted on NVIDIA NIM.',
    specs: {
      contextWindow: '16,384 (16K)',
      maxOutput: '4,096 (4K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      'Punches above weight class in math and STEM reasoning',
      'TensorRT-LLM optimized',
      'High-density synthetic data alignment',
    ],
    pros: ['Superb math and algorithmic logic', 'Fast inference'],
    cons: ['16K context window'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen2.5-72b-instruct',
    name: 'Qwen 2.5 72B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Alibaba Qwen 2.5 72B flagship model with 128K context and outstanding coding and multilingual performance.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'World-leading multilingual and code benchmark scores',
      'Reliable structured JSON output and tool calling',
    ],
    pros: ['Exceptional code and technical reasoning', 'Long context stability'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen2.5-coder-32b-instruct',
    name: 'Qwen 2.5 Coder 32B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Specialized coding model matching larger frontier models on software engineering benchmarks.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'Specialized code generation, debugging, and refactoring',
      'Native function calling and repository understanding',
    ],
    pros: ['Elite programming intelligence', 'High throughput on NVIDIA NIM'],
    cons: ['Specialized for code and technical tasks'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  // ═══════════════════════════════════════════════════════════════════════════════
  // PRESERVED EXISTING NVIDIA NIM MODELS
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'deepseek-ai/deepseek-v4-pro-0813',
    name: 'DeepSeek V4 Pro 0813',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'DeepSeek V4 Pro frontier MoE reasoning and algorithmic coding model with TensorRT-LLM acceleration on NVIDIA DGX Cloud.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '16,384 (16K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '128K Token Context Window with TensorRT-LLM acceleration',
      'Advanced mathematical synthesis, algorithmic coding, and multi-step reasoning',
      'Native tool and function calling support',
      'High-throughput low-latency inference on NVIDIA DGX Cloud infrastructure',
    ],
    pros: [
      'Frontier reasoning accuracy with deep mathematical and code capabilities',
      'Fast token throughput on NVIDIA NIM cluster',
    ],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-3-super-120b-a12b',
    name: 'Nemotron 3 Super',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron 3 Super 120B parameter (12B active) flagship reasoning and coding model with 1M context.',
    specs: {
      contextWindow: '1,048,576 (1M)',
      maxOutput: '262,144 (262K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '1M Token Context Window and 262K Max Output Token capacity',
      'MoE architecture optimized for code generation and technical synthesis',
      'Full function calling and autonomous agent execution',
      'TensorRT-LLM optimized fp8 inference',
    ],
    pros: [
      'Balanced reasoning accuracy and high token throughput',
      'Enormous 262K output generation budget',
    ],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-3-nano-30b-a3b',
    name: 'nemotron-3-nano-30b-a3b',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron 3 Nano 30B lightweight MoE model with 262K context. High throughput and economical resource footprint.',
    specs: {
      contextWindow: '262,144 (262K)',
      maxOutput: '32,768 (32K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: false,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '262K Context Window',
      '30B MoE (3B active) parameter architecture',
      'Fast batch processing, tool integration, and extraction',
    ],
    pros: ['High concurrency and rapid generation for micro-tasks'],
    cons: ['Best suited for direct tasks rather than multi-layered reasoning'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-ultra-253b-v1',
    name: 'Llama 3.1 Nemotron Ultra 253B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron Ultra 253B massive parameter frontier reasoning model with TensorRT-LLM acceleration on NVIDIA DGX Cloud.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '4,096 (4K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '128K Context Window',
      'Ultra-dense 253B parameter reasoning architecture',
      'Advanced mathematical synthesis and code intelligence',
      'Function calling and automated reasoning workflows',
    ],
    pros: [
      'State-of-the-art benchmark reasoning and instruction following',
      'High-throughput inference on NVIDIA NIM clusters',
    ],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta flagship open Llama 3.3 70B model hosted on NVIDIA high-speed NIM infrastructure with TensorRT-LLM acceleration.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '4,096 (4K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'Proven general knowledge, code generation, and multi-step tool use',
      'Native function calling and agentic capabilities',
      'TensorRT-LLM optimized low latency',
    ],
    pros: [
      'Extremely fast response generation on NVIDIA infrastructure',
      'Reliable tool and function calling',
    ],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mistral-nemotron',
    name: 'mistral-nemotron',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral Nemotron high-efficiency reasoning model co-developed and optimized by Mistral AI and NVIDIA.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: false,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'Compact architecture fine-tuned for high throughput and reasoning',
      'Excellent multilingual and code generation accuracy',
      'Tool calling enabled',
    ],
    pros: ['Ultra-fast generation and low memory footprint'],
    cons: ['8K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/gemma-4-31b-it',
    name: 'Gemma-4-31B-IT',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Google Gemma 4 31B instruction model accelerated with TensorRT-LLM on NVIDIA NIM.',
    specs: {
      contextWindow: '262,144 (262K)',
      maxOutput: '8,192 (8K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: false,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '262K Token Long-Context Window',
      'Dense 31B parameter instruction-tuned weights',
      'Tool calling and code analysis support',
      'TensorRT-LLM acceleration on NVIDIA GPU backend',
    ],
    pros: ['Strong coding accuracy and reasoning on high-speed NIM backend'],
    cons: ['8K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mistral-large-2-instruct',
    name: 'Mistral Large 2 Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral AI flagship frontier model with 128K context. Exceptional multilingual fluency, advanced coding, and complex logic.',
    specs: {
      contextWindow: '131,072 (128K)',
      maxOutput: '4,096 (4K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: false,
      toolCalling: true,
    },
    supportsThinking: false,
    features: [
      '128K Context Window',
      'Native function calling and agentic task execution',
      'High-tier benchmark performance on coding and reasoning',
    ],
    pros: ['Enterprise-grade code and logic generation'],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'minimaxai/minimax-m3',
    name: 'MiniMax-M3',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'MiniMax M3 ultra-large scale language model with 1M context window hosted on NVIDIA NIM clusters.',
    specs: {
      contextWindow: '1,048,576 (1M)',
      maxOutput: '65,536 (64K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '1M Token Context Window for massive document ingestion',
      '64K Maximum Output Token capacity',
      'Deep reasoning, creative generation, and tool use',
    ],
    pros: [
      'Extremely large 1M context and ~64K output token budget',
      'Deep context adherence and reasoning',
    ],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-3-ultra-550b-a55b',
    name: 'Nemotron 3 Ultra 550B A55B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron 3 Ultra 550B parameter (55B active) massive-scale enterprise frontier model with 1M context window. Optimized with TensorRT-LLM on NVIDIA DGX Cloud.',
    specs: {
      contextWindow: '1,048,576 (1M)',
      maxOutput: '262,144 (262K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '1M Token Context Window for enterprise codebase and document analysis',
      '550B Parameter MoE Architecture with high reasoning capacity',
      'Strict JSON output and function calling support',
    ],
    pros: [
      'Massive 1M token input and 262K token output capability',
      'Frontier mathematical and algorithmic reasoning',
    ],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'openai/gpt-oss-120b',
    name: 'GPT OSS 120B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'OpenAI 120B open reasoning model hosted on NVIDIA NIM with TensorRT-LLM optimization. High output capacity with 131K context.',
    specs: {
      contextWindow: '131,072 (131K)',
      maxOutput: '131,072 (131K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '131K Token Context Window and 131K Output Limit',
      'TensorRT-LLM accelerated inference on NVIDIA GPU infrastructure',
      'Advanced multi-step reasoning and algorithmic coding',
      'Function calling and structured execution',
    ],
    pros: [
      'Full 131K output capacity matching the context window',
      'Frontier reasoning on NVIDIA NIM',
    ],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'openai/gpt-oss-20b',
    name: 'GPT OSS 20B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'OpenAI 20B lightweight reasoning model hosted on NVIDIA NIM with TensorRT-LLM optimization.',
    specs: {
      contextWindow: '131,072 (131K)',
      maxOutput: '131,072 (131K)',
      modality: 'Text',
    },
    capabilities: {
      vision: false,
      reasoning: true,
      toolCalling: true,
    },
    supportsThinking: true,
    features: [
      '131K Token Context Window and 131K Output Limit',
      'High-speed generation on NVIDIA NIM backend',
      'Reliable instruction adherence and structured data extraction',
      'Tool calling enabled',
    ],
    pros: [
      'Ultra-fast generation with full 131K output token capacity',
      'Economical latency with strong reasoning abilities',
    ],
    cons: ['Text-only modality'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FULL NVIDIA NIM CATALOG FROM SCREENSHOTS (IMAGE 1 to IMAGE 5)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'nvidia/nemotron-3.5-lightning-30b-a3b',
    name: 'Nemotron 3.5 Lightning 30B A3B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron 3.5 Lightning 30B active-parameter MoE model engineered for ultra-fast reasoning and code workflows.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context window',
      'Lightning-fast token throughput',
      'Tool calling and JSON schemas',
    ],
    pros: ['Ultra-low latency', 'Solid coding performance'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/muse-glimmer-30b',
    name: 'Muse Glimmer 30B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Muse Glimmer 30B specialized creative and structured prose generation model with deep narrative coherence.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: false },
    supportsThinking: true,
    features: ['128K context window', 'Creative prose synthesis', 'Long-form coherence'],
    pros: ['Rich stylistic range', 'Nuanced prose'],
    cons: ['No tool calling'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'deepseek-ai/deepseek-v4-flash-0731',
    name: 'DeepSeek V4 Flash 0731',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'DeepSeek V4 Flash high-speed MoE model optimized on TensorRT-LLM with fast chain-of-thought mathematical reasoning.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '16,384 (16K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context window', 'Rapid reasoning tokens', 'Full function calling'],
    pros: ['Extremely fast', 'Deep reasoning'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'deepseek-ai/deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'DeepSeek V4 Flash production release with high-efficiency reasoning, coding, and mathematical proofs.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '16,384 (16K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context window', 'DeepSeek MoE architecture', 'Tool use enabled'],
    pros: ['High throughput', 'Strong coding scores'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'deepseek-ai/deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'DeepSeek V4 Pro frontier MoE reasoning and coding model with deep reasoning and TensorRT-LLM speed.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '16,384 (16K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context window',
      'Frontier mathematical accuracy',
      'Complex software engineering',
    ],
    pros: ['State-of-the-art reasoning', 'Agentic workflow power'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'moonshotai/kimi-k3',
    name: 'Kimi K3',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Moonshot AI Kimi K3 long-context model with 256K context window, mathematical reasoning, and web-scale tool integration.',
    specs: { contextWindow: '262,144 (256K)', maxOutput: '16,384 (16K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '256K token context window',
      'Advanced research synthesis',
      'Tool and search integration',
    ],
    pros: ['Massive context window', 'Rigorous citations'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/inkling',
    name: 'Inkling',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Inkling ultra-fast micro-model designed for real-time text parsing, grammar normalization, and instant completions.',
    specs: { contextWindow: '65,536 (64K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['64K context', 'Sub-millisecond TTFT', 'Grammar corrections'],
    pros: ['Near-instant output'],
    cons: ['Basic reasoning'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/laguna-xs-2.1',
    name: 'Laguna XS 2.1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Laguna XS 2.1 edge-optimized instruction model with function calling and API orchestration.',
    specs: { contextWindow: '65,536 (64K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['64K context', 'Fast agent tool routing', 'Structured JSON outputs'],
    pros: ['Lightweight and efficient'],
    cons: ['Simple reasoning'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'thudm/glm-5.2',
    name: 'GLM-5.2',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Tsinghua / Zhipu AI GLM-5.2 bilingual frontier model with advanced code generation, reasoning, and tool use.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context window',
      'Deep bilingual English/Chinese comprehension',
      'Complex code architecture',
    ],
    pros: ['Excellent technical writing and coding'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'stepfun-ai/step-3.7-flash',
    name: 'Step 3.7 Flash',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'StepFun Step 3.7 Flash high-throughput reasoning model with fast step-by-step thinking and tool execution.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Step-by-step logic verification', 'Tool calling'],
    pros: ['High throughput', 'Strong problem solving'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'stepfun-ai/step-3.5-flash',
    name: 'Step 3.5 Flash',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'StepFun Step 3.5 Flash efficient reasoning model for coding, logical deductions, and data extraction.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Fast mathematical processing', 'Function calling'],
    pros: ['Economical latency'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mistral-medium-3.5',
    name: 'Mistral Medium 3.5',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral Medium 3.5 frontier model balancing enterprise coding, multilingual fluency, and native tool calling.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Enterprise coding benchmarks', 'Function calling'],
    pros: ['Accurate tool execution', 'Multilingual strength'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mistral-medium-3',
    name: 'Mistral Medium 3',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'Mistral Medium 3 high-performance instruction and agentic automation model.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Tool integration', 'JSON schemas'],
    pros: ['Stable and consistent'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-3-nano-omni',
    name: 'Nemotron 3 Nano Omni',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron 3 Nano Omni multimodal vision, audio, and text comprehension model with real-time processing.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: [
      '128K context',
      'Vision & Audio multimodal ingestion',
      'Real-time scene interpretation',
    ],
    pros: ['Multimodal versatility', 'Fast inference'],
    cons: ['Lower complex reasoning'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/active-speaker-detection',
    name: 'Active Speaker Detection',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA specialized NIM for visual and acoustic active speaker tracking and diarization.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '2,048 (2K)', modality: 'Vision/Audio' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Video and audio stream processing', 'Sub-frame precision speaker tracking'],
    pros: ['Industry-standard diarization'],
    cons: ['Specialized vision-audio model'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-3-content-safety',
    name: 'nemotron-3-content-safety',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron 3 Content Safety guardrail classifier for policy compliance, prompt injection, and toxicity moderation.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '2,048 (2K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Guardrail classification', 'Low latency safety checks'],
    pros: ['Accurate moderation'],
    cons: ['Classifier only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/synthetic-video-detector',
    name: 'synthetic-video-detector',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA vision model specialized in detecting AI-generated synthetic video artifacts and deepfakes.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Deepfake analysis', 'Artifact detection'],
    pros: ['Visual verification precision'],
    cons: ['Vision classifier'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-nemotron-rerank-vl-1b-v2',
    name: 'llama-nemotron-rerank-vl-1b-v2',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Vision-Language Reranker 1B v2 for multimodal RAG retrieval across visual documents, diagrams, and text.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '1,024 (1K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Multimodal document reranking', 'High-accuracy retrieval augmentation'],
    pros: ['State-of-the-art vision-text RAG'],
    cons: ['Reranker model'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'minimaxai/minimax-m2.7',
    name: 'MiniMax-M2.7',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'MiniMax M2.7 large language model with 512K context window, advanced reasoning, and creative synthesis.',
    specs: { contextWindow: '524,288 (512K)', maxOutput: '32,768 (32K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '512K token context window',
      'High multilingual fluency',
      'Code and agent workflows',
    ],
    pros: ['Massive context window', 'Rich stylistic generation'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mistral-small-4-119b-2603',
    name: 'mistral-small-4-119b-2603',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral Small 4 119B MoE instruction model fine-tuned for high-speed reasoning, coding, and function calling.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'MoE architecture', 'Function calling'],
    pros: ['Fast token output', 'Compact and accurate'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-voicechat',
    name: 'nemotron-voicechat',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron VoiceChat real-time conversational speech-to-speech and low-latency dialogue microservice.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Audio/Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Real-time speech dialogue', 'Low latency turn-taking'],
    pros: ['Ultra-responsive conversational audio'],
    cons: ['Speech dialogue focused'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/gliner-pii',
    name: 'gliner-pii',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA GLiNER-PII zero-shot Personally Identifiable Information (PII) extraction and redaction model.',
    specs: { contextWindow: '16,384 (16K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Zero-shot entity recognition', 'Automated privacy redaction'],
    pros: ['Fast and accurate PII detection'],
    cons: ['NER specific'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/cosmos-transfer2.5-2b',
    name: 'cosmos-transfer2.5-2b',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Cosmos Transfer 2.5 2B physical AI generative world model for video generation and visual simulation.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Physical simulation transfer', 'World-space video generation'],
    pros: ['Advanced physical visual modeling'],
    cons: ['Generative visual simulation only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen3.5-122b-a10b',
    name: 'Qwen3.5 122B-A10B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Alibaba Qwen3.5 122B MoE (10B active) model with deep mathematical reasoning, coding, and tool calling.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'MoE architecture', 'Deep mathematical logic', 'Full tool calling'],
    pros: ['Exceptional code and logic synthesis'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen3.5-397b-a17b',
    name: 'Qwen3.5-397B-A17B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Alibaba Qwen3.5 397B flagship MoE (17B active) frontier model with state-of-the-art coding and reasoning scores.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context window', '397B massive MoE weights', 'Complex software engineering'],
    pros: ['Frontier coding and reasoning benchmarks'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-nemotron-embed-vl-1b-v2',
    name: 'llama-nemotron-embed-vl-1b-v2',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Vision-Language 1B embedding model for dense vector indexing across images, diagrams, and text.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '1,024 (1K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Multimodal vector embeddings', 'Dense retrieval indexing'],
    pros: ['High retrieval precision on diagrams and charts'],
    cons: ['Embedding model only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-content-safety-reasoning-4b',
    name: 'nemotron-content-safety-reasoning-4b',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron 4B safety model with explainable chain-of-thought safety reasoning and policy justification.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: false },
    supportsThinking: true,
    features: ['Explainable safety reasoning', 'Audit trail generation'],
    pros: ['Detailed policy reasoning'],
    cons: ['Safety focused'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'black-forest-labs/flux.2-klein-4b',
    name: 'FLUX.2 Klein 4B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Black Forest Labs FLUX.2 Klein 4B high-speed image generation and visual reasoning diffusion model.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['High-fidelity visual generation', 'Diffusion transformer'],
    pros: ['Photorealistic images at rapid speed'],
    cons: ['Visual generation model'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/usdcode',
    name: 'usdcode',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Universal Scene Description (USD) code generator for 3D worlds, Omniverse scene graphs, and Python USD scripts.',
    specs: { contextWindow: '65,536 (64K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['OpenUSD scripting', 'Omniverse scene generation', 'Python pxr library expertise'],
    pros: ['Unmatched 3D USD code generation'],
    cons: ['Domain-specific to 3D USD'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/riva-translate-4b-instruct-v1_1',
    name: 'riva-translate-4b-instruct-v1_1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Riva 4B Neural Machine Translation model supporting 50+ languages with low-latency streaming.',
    specs: { contextWindow: '16,384 (16K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['50+ language translation', 'High-speed translation engine'],
    pros: ['Accurate cross-lingual preservation'],
    cons: ['Translation specific'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/ministral-3-14b-instruct-2512',
    name: 'Ministral 3 14B Instruct 2512',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral AI Ministral 3 14B state-of-the-art compact instruction model with 128K context and native tool calling.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'High speed edge deployment', 'Function calling'],
    pros: ['Very fast generation', 'Accurate tool use'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mistral-large-3-675b-instruct-2512',
    name: 'Mistral Large 3 675B Instruct 2512',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral AI flagship 675B frontier MoE model with deep mathematical logic, code synthesis, and multi-agent coordination.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Frontier code generation', 'Complex agent coordination'],
    pros: ['Top-tier multilingual code intelligence'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/cosmos-reason2-8b',
    name: 'Cosmos Reason2 8B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Cosmos Reason2 8B multimodal reasoning model for physical simulation, robotics, and visual spatio-temporal logic.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: true, toolCalling: false },
    supportsThinking: true,
    features: [
      '128K context',
      'Visual-spatial physical reasoning',
      'Robotics and world simulation',
    ],
    pros: ['Deep physical intuition and visual logic'],
    cons: ['No tool calling'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/streampetr',
    name: 'streampetr',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA StreamPETR point-cloud and multi-camera 3D temporal object perception microservice for autonomous navigation.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Temporal multi-camera 3D tracking', 'Real-time scene geometry'],
    pros: ['Autonomous perception accuracy'],
    cons: ['Autonomous driving specific'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-nano-12b-v2-vl',
    name: 'Nemotron Nano 12B v2 VL',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron Nano 12B v2 Vision-Language model with multimodal image reasoning, chart understanding, and tool use.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context',
      'Multimodal image and document comprehension',
      'Tool calling and JSON extraction',
    ],
    pros: ['Versatile vision + reasoning + tools'],
    cons: ['8K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-safety-guard-8b-v3',
    name: 'llama-3.1-nemotron-safety-guard-8b-v3',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Llama 3.1 Nemotron Safety Guard 8B v3 high-accuracy input and output moderation classifier.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '2,048 (2K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['OWASP Top 10 for LLMs protection', 'Prompt injection mitigation'],
    pros: ['Fast guardrail enforcement'],
    cons: ['Classifier only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/magistral-small-2506',
    name: 'Magistral Small 2506',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral Magistral Small 2506 advanced reasoning and instruction model with high algorithmic coding performance.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Reasoning token stream', 'Agent tool use'],
    pros: ['High mathematical accuracy'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'bytedance-seed/seed-oss-36b-instruct',
    name: 'ByteDance-Seed/Seed-OSS-36B-Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'ByteDance Seed OSS 36B open-weights instruction model with deep reasoning and coding proficiency.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Code generation and reasoning', 'Tool calling'],
    pros: ['Strong multi-turn coding'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen-image-edit',
    name: 'Qwen Image Edit',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Alibaba Qwen Image Edit multimodal instruction-based image manipulation and visual editing model.',
    specs: { contextWindow: '16,384 (16K)', maxOutput: '4,096 (4K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Visual prompt instruction', 'Semantic inpainting and editing'],
    pros: ['Precise localized visual modifications'],
    cons: ['Image editing focused'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-nano-9b-v2',
    name: 'nvidia-nemotron-nano-9b-v2',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron Nano 9B v2 fast instruction model with function calling and compact memory footprint.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Native function calling', 'TensorRT-LLM optimized'],
    pros: ['Ultra-low latency inference'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'black-forest-labs/flux.1-kontext-dev',
    name: 'FLUX.1-Kontext-dev',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Black Forest Labs FLUX.1 Kontext Dev text-to-image foundation model with dense visual typography and prompt fidelity.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Photorealistic visual rendering', 'Accurate in-image text generation'],
    pros: ['Highest visual quality and text precision'],
    cons: ['Image generation only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen-image',
    name: 'Qwen Image',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'Alibaba Qwen Image visual comprehension and image question answering model.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Detailed image captioning', 'Visual visual entity question answering'],
    pros: ['High visual recognition accuracy'],
    cons: ['No tool calling'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'microsoft/phi-4-multimodal-instruct',
    name: 'Phi 4 Multimodal',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Microsoft Phi-4 Multimodal compact frontier model with speech, image, and text reasoning capabilities.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Image and speech input', 'Mathematical logic and tool calling'],
    pros: ['Compact multi-modal powerhouse', 'Fast response time'],
    cons: ['8K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
    name: 'Llama 3.3 Nemotron Super 49B v1.5',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron Super 49B v1.5 fine-tuned on Llama 3.3 for high-throughput reasoning and agent planning.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Super-alignment tuning', 'Native function calling'],
    pros: ['High reasoning density', 'Strong tool reliability'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'sarvamai/sarvam-m',
    name: 'sarvam-m',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Sarvam AI foundational multilingual model specialized for Indic languages, code switching, and regional context.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['10+ Indic languages', 'Script transliteration', 'Tool calling'],
    pros: ['Top accuracy on Indian languages and cultural context'],
    cons: ['32K context'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.2-nemoretriever-300m-embed-v1',
    name: 'llama-3_2-nemoretriever-300m-embed-v1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA NeMo Retriever 300M dense text embedding model with state-of-the-art MTEB retrieval accuracy.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '1,024 (1K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Dense semantic embeddings', 'High MTEB benchmark score'],
    pros: ['Ultra-fast vector search indexing'],
    cons: ['Embedding model only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen3-coder-480b-a35b-instruct',
    name: 'Qwen3 Coder 480B A35B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Alibaba Qwen3 Coder 480B MoE (35B active) flagship coding model with advanced codebase synthesis and bug diagnosis.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context window',
      'Enterprise code generation',
      'Native AST understanding and tool calling',
    ],
    pros: ['World-class software engineering intelligence'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/cosmos-transfer1-7b',
    name: 'cosmos-transfer1-7b',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Cosmos Transfer 1 7B generative world simulation model for video synthesis.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Generative visual simulation', 'Physics-informed diffusion'],
    pros: ['Realistic world physics simulation'],
    cons: ['Visual generation only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/gemma-3n-e2b-it',
    name: 'Gemma 3n E2b It',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Google Gemma 3n 2B effective instruction model optimized for ultra-fast response times on edge devices.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['32K context', 'Ultra-low resource usage', 'Function calling'],
    pros: ['Near-zero latency'],
    cons: ['Simpler tasks only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/gemma-3n-e4b-it',
    name: 'Gemma 3n E4b It',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Google Gemma 3n 4B effective instruction model with balanced reasoning and low memory footprint.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['32K context', 'Fast instruction following', 'Function calling'],
    pros: ['Very responsive and concise'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/magpie-tts-zeroshot',
    name: 'magpie-tts-zeroshot',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'NVIDIA Magpie zero-shot neural Text-To-Speech audio synthesis microservice.',
    specs: { contextWindow: '16,384 (16K)', maxOutput: '2,048 (2K)', modality: 'Audio' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Zero-shot voice cloning', 'Natural prosody generation'],
    pros: ['High acoustic fidelity'],
    cons: ['TTS audio specific'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    name: 'Llama 3.1 Nemotron 70B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA fine-tuned Llama 3.1 70B model with exceptional reasoning, math, and instruction following scores.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'High benchmark reasoning', 'Native tool use'],
    pros: ['Proven enterprise reasoning accuracy'],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-nano-vl-8b-v1',
    name: 'Llama 3.1 Nemotron Nano VL 8B v1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Llama 3.1 Nemotron Vision-Language 8B model for image understanding and document OCR analysis.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Image and diagram analysis', 'Tool use'],
    pros: ['Fast vision processing on NIM'],
    cons: ['Moderate reasoning'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.3-nemotron-super-49b-v1',
    name: 'Llama 3.3 Nemotron Super 49B v1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron Super 49B v1 high-density reasoning model with deep instruction following.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'High throughput', 'Tool calling'],
    pros: ['Strong multi-turn logic'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-guard-4-12b',
    name: 'Llama Guard 4 12B',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta Llama Guard 4 12B safety and moderation model for AI trust and safety compliance.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Safety taxonomy compliance', 'Content moderation'],
    pros: ['Standardized safety guard'],
    cons: ['Classifier only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-4-maverick-17b-128e-instruct',
    name: 'Llama 4 Maverick 17b 128e Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta Llama 4 Maverick 17B MoE (128 experts) multimodal instruction model with vision and coding.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context window',
      '128-expert MoE architecture',
      'Vision, reasoning, and tool calling',
    ],
    pros: ['Next-generation MoE efficiency and multimodal intelligence'],
    cons: ['8K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mistral-7b-instruct-v0.3',
    name: 'Mistral-7B-Instruct-v0.3',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral 7B Instruct v0.3 high-speed compact model with function calling and 32K context.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['32K context', 'Native function calling', 'JSON mode'],
    pros: ['Lightning fast generation'],
    cons: ['Smaller capacity for complex tasks'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-nano-8b-v1',
    name: 'Llama 3.1 Nemotron Nano 8B v1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron Nano 8B v1 instruction model for rapid text processing and tool orchestration.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Function calling', 'TensorRT-LLM optimized'],
    pros: ['High throughput and low memory footprint'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/bevformer',
    name: 'bevformer',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Bird-Eye-View Former spatio-temporal transformer for 3D visual perception.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['BEV visual projection', 'Multi-camera perception'],
    pros: ['Precise 3D spatial mapping'],
    cons: ['Vision transformer only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/cosmos-predict1-5b',
    name: 'cosmos-predict1-5b',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Cosmos Predict 1 5B generative trajectory forecasting and physical world state model.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Trajectory prediction', 'World model simulation'],
    pros: ['Accurate physical dynamics forecasting'],
    cons: ['Simulation model only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/sparsedrive',
    name: 'sparsedrive',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA SparseDrive end-to-end autonomous driving perception and trajectory planning microservice.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Sparse visual perception', 'Motion planning'],
    pros: ['High-speed autonomous navigation planning'],
    cons: ['Robotics only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nv-embedcode-7b-v1',
    name: 'nv-embedcode-7b-v1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Code Embedding 7B v1 for semantic source code retrieval, symbol search, and repository RAG.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '1,024 (1K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Dense code embedding vectors', 'Repository AST search'],
    pros: ['Superior code search accuracy'],
    cons: ['Embedding model only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/gemma-3-12b-it',
    name: 'Gemma 3 12B IT',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Google Gemma 3 12B Instruction-Tuned model with native vision and high-efficiency text reasoning.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Multimodal vision and text', 'Tool calling enabled'],
    pros: ['Strong vision and instruction accuracy'],
    cons: ['8K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/gemma-3-4b-it',
    name: 'Gemma 3 4B IT',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Google Gemma 3 4B Instruction-Tuned lightweight multimodal model for fast text and image comprehension.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Vision understanding', 'Function calling'],
    pros: ['Very fast multimodal model'],
    cons: ['Moderate reasoning complexity'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.1-8b-instruct',
    name: 'Llama 3.1 8B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta Llama 3.1 8B instruction model with 128K context and native tool calling on NVIDIA NIM.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Function calling', 'Fast response generation'],
    pros: ['High throughput for everyday tasks'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'microsoft/phi-4-mini-instruct',
    name: 'Phi-4-Mini',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Microsoft Phi-4 Mini 3.8B model with exceptional reasoning, math, and code capabilities.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Frontier mathematical accuracy in small weights', 'Tool calling'],
    pros: ['Best-in-class small reasoning model'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen3-next-80b-a3b-instruct',
    name: 'Qwen3-Next-80B-A3B-Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Alibaba Qwen3 Next 80B MoE (3B active) next-generation model with deep reasoning and coding.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'Ultra-sparse MoE efficiency', 'Tool calling and coding'],
    pros: ['High throughput with frontier logic'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'qwen/qwen2.5-coder-32b-instruct',
    name: 'Qwen2.5 Coder 32b Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Alibaba Qwen 2.5 Coder 32B specialized coding model with 128K context and native tool calling.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '8,192 (8K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context',
      'State-of-the-art coding accuracy',
      'Multi-language code synthesis and debugging',
    ],
    pros: ['Top-tier coding benchmark performance'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/studiovoice',
    name: 'studiovoice',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA StudioVoice AI studio-grade voice enhancement and room acoustics normalization.',
    specs: { contextWindow: '16,384 (16K)', maxOutput: '2,048 (2K)', modality: 'Audio' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Studio audio enhancement', 'Noise and room echo reduction'],
    pros: ['Broadcast quality vocal cleanup'],
    cons: ['Audio specific'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.2-90b-vision-instruct',
    name: 'Llama-3.2-90B-Vision-Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta Llama 3.2 90B flagship vision-language model for deep visual reasoning, OCR, and diagram analysis.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: [
      '128K context',
      'Multimodal image comprehension',
      'Complex visual reasoning and tool calling',
    ],
    pros: ['Frontier vision and reasoning capability'],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.2-11b-vision-instruct',
    name: 'Llama 3.2 11b Vision Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta Llama 3.2 11B multimodal vision-language model with fast visual extraction and document analysis.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Image and chart analysis', 'Function calling'],
    pros: ['Fast multimodal inference'],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.2-1b-instruct',
    name: 'Llama 3.2 1b Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta Llama 3.2 1B ultra-compact instruction model for lightweight on-device and edge tasks.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '2,048 (2K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['128K context', 'Ultra-fast token throughput'],
    pros: ['Minimal latency and footprint'],
    cons: ['Limited complex reasoning'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.2-3b-instruct',
    name: 'Llama 3.2 3B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'Meta Llama 3.2 3B compact model with tool calling and instruction following.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '2,048 (2K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Function calling', 'JSON extraction'],
    pros: ['Fast and reliable on micro-tasks'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/dracarys-llama-3.1-70b-instruct',
    name: 'dracarys-llama-3.1-70b-instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Dracarys fine-tuned Llama 3.1 70B specialized for deep reasoning and synthetic data curation.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['128K context', 'High-fidelity alignment', 'Tool calling'],
    pros: ['Exceptional instruction adherence'],
    cons: ['Text-only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/esm2-650m',
    name: 'esm2-650m',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta / NVIDIA Evolutionary Scale Modeling 2 650M protein language model for biological sequence analysis.',
    specs: {
      contextWindow: '8,192 (8K)',
      maxOutput: '2,048 (2K)',
      modality: 'Biological Sequence',
    },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Protein structure prediction', 'Biochemical sequence embeddings'],
    pros: ['Accurate biological protein representations'],
    cons: ['Biomedical domain only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nemotron-mini-4b-instruct',
    name: 'nemotron-mini-4b-instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Nemotron Mini 4B compact instruction model optimized for responsive tool calling.',
    specs: { contextWindow: '4,096 (4K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['Function calling', 'Fast on-device response times'],
    pros: ['Very fast TTFT'],
    cons: ['4K context limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'black-forest-labs/flux.1-dev',
    name: 'FLUX.1-dev',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Black Forest Labs FLUX.1 Dev open-weights 12B parameter text-to-image diffusion transformer.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['High-resolution 1024x1024 generation', 'Complex prompt understanding'],
    pros: ['State-of-the-art artistic image synthesis'],
    cons: ['Image generation only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'black-forest-labs/flux.1-schnell',
    name: 'FLUX.1-schnell',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Black Forest Labs FLUX.1 Schnell ultra-fast 1-4 step latent diffusion image generation model.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '2,048 (2K)', modality: 'Vision' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['1-4 step ultra-fast image generation', 'High prompt fidelity'],
    pros: ['Sub-second image synthesis'],
    cons: ['Image generation only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/usdvalidate',
    name: 'usdvalidate',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Universal Scene Description (USD) compliance, geometry, and asset validation microservice.',
    specs: { contextWindow: '16,384 (16K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['OpenUSD schema validation', '3D pipeline compliance'],
    pros: ['Deterministic 3D USD checks'],
    cons: ['USD specific'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/gemma-2-2b-it',
    name: 'Gemma 2 2b It',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'Google Gemma 2 2B compact instruction model with fast inference on NVIDIA NIM.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['8K context', 'Fast text completion'],
    pros: ['Compact resource footprint'],
    cons: ['No tool calling'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'meta/llama-3.1-70b-instruct',
    name: 'Llama 3.1 70b Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Meta Llama 3.1 70B instruction model with 128K context and native tool calling on NVIDIA NIM.',
    specs: { contextWindow: '131,072 (128K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: false,
    features: ['128K context', 'Enterprise coding and reasoning', 'Function calling'],
    pros: ['High reliability across benchmarks'],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/nv-embed-v1',
    name: 'nv-embed-v1',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Embed v1 leading text embedding model on the Massive Text Embedding Benchmark (MTEB).',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '1,024 (1K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Top MTEB retrieval performance', 'High-dimensional semantic embeddings'],
    pros: ['Industry-leading search precision'],
    cons: ['Embedding model only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'upstage/solar-10.7b-instruct',
    name: 'solar-10.7b-instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Upstage Solar 10.7B Depth-Up-Scaled instruction model with tool calling and high reasoning speed.',
    specs: { contextWindow: '4,096 (4K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['DUS architecture', 'Function calling', 'JSON mode'],
    pros: ['Strong benchmark performance for size'],
    cons: ['4K context limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'google/paligemma',
    name: 'paligemma',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Google PaliGemma 3B vision-language model for image captioning, visual Q&A, and object segmentation.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '2,048 (2K)', modality: 'Multimodal' },
    capabilities: { vision: true, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Visual question answering', 'Bounding-box detection'],
    pros: ['Compact multimodal vision'],
    cons: ['No tool calling'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mixtral-8x22b-instruct-v0.1',
    name: 'Mistral: Mixtral 8x22B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral Mixtral 8x22B high-capacity MoE model with 64K context, advanced coding, and function calling.',
    specs: { contextWindow: '65,536 (64K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: true, toolCalling: true },
    supportsThinking: true,
    features: ['64K context window', 'MoE architecture with 176B total params', 'Function calling'],
    pros: ['State-of-the-art math and code synthesis'],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/rerank-qa-mistral-4b',
    name: 'rerank-qa-mistral-4b',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'NVIDIA Mistral-based 4B cross-encoder model for question-answering reranking in RAG pipelines.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '1,024 (1K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Cross-encoder relevance scoring', 'RAG search optimization'],
    pros: ['Drastically improves retrieval accuracy'],
    cons: ['Reranker only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'nvidia/esmfold',
    name: 'esmfold',
    provider: 'nvidia-nim',
    status: 'ga',
    description: 'NVIDIA / Meta ESMFold high-speed 3D protein structure prediction microservice.',
    specs: {
      contextWindow: '4,096 (4K)',
      maxOutput: '4,096 (4K)',
      modality: 'Biological Structure',
    },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Fast atomic-level protein folding', 'PDB file export'],
    pros: ['Up to 60x faster than AlphaFold2'],
    cons: ['Biochemical protein folding only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'baai/bge-m3',
    name: 'BGE M3',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'BAAI BGE-M3 multi-linguality, multi-functionality, and multi-granularity dense/sparse embedding model.',
    specs: { contextWindow: '8,192 (8K)', maxOutput: '1,024 (1K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Dense, lexical, and multi-vector retrieval in 100+ languages'],
    pros: ['Versatile hybrid retrieval'],
    cons: ['Embedding model only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'mistralai/mixtral-8x7b-instruct-v0.1',
    name: 'Mistral: Mixtral 8x7B Instruct',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'Mistral Mixtral 8x7B flagship sparse MoE model with 32K context and native tool calling.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Text' },
    capabilities: { vision: false, reasoning: false, toolCalling: true },
    supportsThinking: false,
    features: ['32K context', 'Sparse Mixture-of-Experts', 'Function calling'],
    pros: ['High throughput and excellent reasoning for size'],
    cons: ['4K output limit'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
  {
    id: 'openai/whisper-large-v3',
    name: 'Whisper Large v3',
    provider: 'nvidia-nim',
    status: 'ga',
    description:
      'OpenAI Whisper Large v3 automatic speech recognition (ASR) model accelerated with TensorRT-LLM.',
    specs: { contextWindow: '32,768 (32K)', maxOutput: '4,096 (4K)', modality: 'Audio' },
    capabilities: { vision: false, reasoning: false, toolCalling: false },
    supportsThinking: false,
    features: ['Multilingual speech transcription', 'Timestamp alignment and translation'],
    pros: ['Industry-leading speech transcription accuracy'],
    cons: ['Speech-to-text only'],
    limits: { rpm: 40, tpm: null, rpd: 10000 },
  },
];
